version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
    timezone: Canada/Eastern
  open-pull-requests-limit: 2
  ignore:
  - dependency-name: web-ext
    versions:
    - 6.0.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.3.4
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.12
