version: 2.1

# Defaults: shared across jobs

defaults: &defaults
    docker:
        - image: circleci/node:latest
    working_directory: ~/repo

# Commands: reusable command steps that jobs can run

commands:
  prep:
    description: "Prepares environment"
    steps:
        - checkout:
            path: ~/repo

        - restore_cache:
            name: Restore cache
            key: forest-tree-{{ .Branch }}-{{ checksum "yarn.lock" }}{{ .Environment.CACHE_KEY }}

        - run:
            name: "Install yvm"
            command: "curl -s https://raw.githubusercontent.com/tophat/yvm/master/scripts/install.js | node"

  cache:
    description: "Cache environment"
    steps:
      - save_cache:
          name: Save cache
          key: forest-tree-{{ .Branch }}-{{ checksum "yarn.lock" }}{{ .Environment.CACHE_KEY }}
          paths:
            - ~/.yvm/
            - ./node_modules/

# Jobs: tasks that your CI pipeline can do

jobs:
    setup:
        <<: *defaults
        steps:
            - prep
            - run: yarn
            - cache

    lint:
        <<: *defaults
        steps:
            - prep
            - run: yarn lint

    test:
        <<: *defaults
        steps:
            - prep
            - run: yarn test-coverage

    build:
        <<: *defaults
        steps:
            - prep
            - run: yarn build
            - persist_to_workspace:
                root: ~/repo
                paths:
                  - ./

    deploy:
        <<: *defaults
        steps:
            - prep
            - attach_workspace:
                at: ~/repo
            - run: yarn release

# Workflows: stringing jobs together into a pipeline

workflows:
    version: 2
    build_test_lint:
        jobs:
            - setup
            - lint:
                requires:
                    - setup
            - test:
                requires:
                    - setup
            - build:
                requires:
                    - setup
            - deploy:
                requires:
                    - lint
                    - test
                    - build
                # *
                # Deploy job uses semantic-release which filters by branch
                # it runs in dry mode when the branch does not match master
                # which is useful for catching misconfiguration
                # see: `yarn release`
                # *
                # filters:
                #     branches:
                #         only:
                #             - master
