version: 2.1

# Jobs: tasks that your CI pipeline can do

jobs:
    lint:
        working_directory: ~/repo
        # Pick a Docker image here: https://circleci.com/docs/2.0/circleci-images/
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: yarn lint

    test:
        working_directory: ~/repo
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: yarn test-coverage

    build:
        working_directory: ~/repo
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: yarn build

    deploy:
        working_directory: ~/repo
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: yarn release

# Workflows: stringing jobs together into a pipeline

workflows:
    version: 2
    build_test_lint:
        jobs:
            - lint
            - test
            - build
            - deploy:
                requires:
                    - lint
                    - test
                    - build
                # *
                # Deploy job uses semantic-release which filters by branch
                # it runs in dry mode when the branch does not match master
                # which is useful for catching misconfiguration
                # see: `yarn release`
                # *
                # filters:
                #     branches:
                #         only:
                #             - master
