name: Semantic Release Firefox Add-on CICD
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14']
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ci
      - name: Build
        run: yarn build
  e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14']   
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ci
      - name: E2E
        run: |
          cd e2e
          yarn test-e2e
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14']   
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ci
      - name: Test
        run: |
          yarn test-coverage
      - uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: artifacts/coverage
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ci
      - uses: actions/download-artifact@v2
        with:
          name: coverage-report
      - name: Test
        run: |
          yarn report-coverage
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ci
      - name: Lint
        run: yarn lint

